<a href="https://colab.research.google.com/github/juvi-160/IIIT-H-Internship/blob/main/python_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
school = pd.read_csv('https://github.com/YBI-Foundation/Dataset/raw/main/School%20Ratings.csv')

In [3]:
school.head()

,name,school_rating,size,reduced_lunch,state_percentile_16,state_percentile_15,stu_teach_ratio,school_type,avg_score_15,avg_score_16,full_time_teachers,percent_black,percent_white,percent_asian,percent_hispanic
0,Allendale Elementary School,5.0,851.0,10.0,90.2,95.8,15.7,Public,89.4,85.2,54.0,2.9,85.5,1.6,5.6
1,Anderson Elementary,2.0,412.0,71.0,32.8,37.3,12.8,Public,43.0,38.3,32.0,3.9,86.7,1.0,4.9
2,Avoca Elementary,4.0,482.0,43.0,78.4,83.6,16.6,Public,75.7,73.0,29.0,1.0,91.5,1.2,4.4
3,Bailey Middle,0.0,394.0,91.0,1.6,1.0,13.1,Public Magnet,2.1,4.4,30.0,80.7,11.7,2.3,4.3
4,Barfield Elementary,4.0,948.0,26.0,85.3,89.2,14.8,Public,81.3,79.6,64.0,11.8,71.2,7.1,6.0

In [4]:
school.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 347 entries, 0 to 346
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   name                 347 non-null    object
 1   school_rating        347 non-null    float64
 2   size                 347 non-null    float64
 3   reduced_lunch        347 non-null    float64
 4   state_percentile_16  347 non-null    float64
 5   state_percentile_15  341 non-null    float64
 6   stu_teach_ratio      347 non-null    float64
 7   school_type          347 non-null    object
 8   avg_score_15         341 non-null    float64
 9   avg_score_16         347 non-null    float64
 10  full_time_teachers   347 non-null    float64
 11  percent_black        347 non-null    float64
 12  percent_white        347 non-null    float64
 13  percent_asian        347 non-null    float64
 14  percent_hispanic     347 non-null    float64
dtypes: float64(13), object(2)
memory usage: 40.8+ KB

In [5]:
school.describe()

,school_rating,size,reduced_lunch,state_percentile_16,state_percentile_15,stu_teach_ratio,avg_score_15,avg_score_16,full_time_teachers,percent_black,percent_white,percent_asian,percent_hispanic
count,347.000000,347.000000,347.000000,347.000000,341.000000,347.000000,341.000000,347.000000,347.000000,347.000000,347.000000,347.000000,347.000000
mean,2.968300,699.472622,50.279539,58.801729,58.249267,15.461671,57.004692,57.049856,44.939481,21.197983,61.673487,2.642651,11.164553
std,1.690377,400.598636,25.480236,32.540747,32.702630,5.725170,26.696450,27.968974,22.053386,23.562538,27.274859,3.109629,12.030608
min,0.000000,53.000000,2.000000,0.200000,0.600000,4.700000,1.500000,0.100000,2.000000,0.000000,1.100000,0.000000,0.000000
25%,2.000000,420.500000,30.000000,30.950000,27.100000,13.700000,37.600000,37.000000,30.000000,3.600000,40.600000,0.750000,3.800000
50%,3.000000,595.000000,51.000000,66.400000,65.800000,15.000000,61.800000,60.700000,40.000000,13.500000,68.700000,1.600000,6.400000
75%,4.000000,851.000000,71.500000,88.000000,88.600000,16.700000,79.600000,80.250000,54.000000,28.350000,85.950000,3.100000,13.800000
max,5.000000,2314.000000,98.000000,99.800000,99.800000,111.000000,99.000000,98.900000,140.000000,97.400000,99.700000,21.100000,65.200000

In [6]:
school.describe(include='all')

,name,school_rating,size,reduced_lunch,state_percentile_16,state_percentile_15,stu_teach_ratio,school_type,avg_score_15,avg_score_16,full_time_teachers,percent_black,percent_white,percent_asian,percent_hispanic
count,347,347.000000,347.000000,347.000000,347.000000,341.000000,347.000000,347,341.000000,347.000000,347.000000,347.000000,347.000000,347.000000,347.000000
unique,341,NaN,NaN,NaN,NaN,NaN,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,Liberty Elementary,NaN,NaN,NaN,NaN,NaN,NaN,Public,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,3,NaN,NaN,NaN,NaN,NaN,NaN,292,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,2.968300,699.472622,50.279539,58.801729,58.249267,15.461671,NaN,57.004692,57.049856,44.939481,21.197983,61.673487,2.642651,11.164553
std,NaN,1.690377,400.598636,25.480236,32.540747,32.702630,5.725170,NaN,26.696450,27.968974,22.053386,23.562538,27.274859,3.109629,12.030608
min,NaN,0.000000,53.000000,2.000000,0.200000,0.600000,4.700000,NaN,1.500000,0.100000,2.000000,0.000000,1.100000,0.000000,0.000000
25%,NaN,2.000000,420.500000,30.000000,30.950000,27.100000,13.700000,NaN,37.600000,37.000000,30.000000,3.600000,40.600000,0.750000,3.800000
50%,NaN,3.000000,595.000000,51.000000,66.400000,65.800000,15.000000,NaN,61.800000,60.700000,40.000000,13.500000,68.700000,1.600000,6.400000
75%,NaN,4.000000,851.000000,71.500000,88.000000,88.600000,16.700000,NaN,79.600000,80.250000,54.000000,28.350000,85.950000,3.100000,13.800000
max,NaN,5.000000,2314.000000,98.000000,99.800000,99.800000,111.000000,NaN,99.000000,98.900000,140.000000,97.400000,99.700000,21.100000,65.200000

In [7]:
#display shape
school.shape

(347, 15)

In [8]:
#display column labels
school.columns

Index(['name', 'school_rating', 'size', 'reduced_lunch', 'state_percentile_16',
       'state_percentile_15', 'stu_teach_ratio', 'school_type', 'avg_score_15',
       'avg_score_16', 'full_time_teachers', 'percent_black', 'percent_white',
       'percent_asian', 'percent_hispanic'],
      dtype='object')

In [9]:
#select a column as a series
school['name']

0       Allendale Elementary School
1               Anderson Elementary
2                  Avoca Elementary
3                     Bailey Middle
4               Barfield Elementary
                   ...
342    Winfree Bryant Middle School
343      Winstead Elementary School
344             Woodland Elementary
345          Woodland Middle School
346                   Wright Middle
Name: name, Length: 347, dtype: object

In [10]:
school['name'].shape

(347,)

In [11]:
#selecy a column as a dataframe
school[['name']]

                             name
0     Allendale Elementary School
1             Anderson Elementary
2                Avoca Elementary
3                   Bailey Middle
4             Barfield Elementary
..                            ...
342  Winfree Bryant Middle School
343    Winstead Elementary School
344           Woodland Elementary
345        Woodland Middle School
346                 Wright Middle

[347 rows x 1 columns]

In [12]:
#unique categories in a column
school['name'].unique()

array(['Allendale Elementary School', 'Anderson Elementary',
       'Avoca Elementary', 'Bailey Middle', 'Barfield Elementary',
       'Barkers Mill Elementary School', 'Barksdale Elementary',
       'Beech Elementary', 'Beech Senior High School', 'Bellevue Middle',
       'Bellshire Elementary', 'Benny C. Bills Elementary School',
       'Black Fox Elementary', 'Blackman Elementary School',
       'Blackman High School', 'Blackman Middle School',
       'Bluff City Elementary', 'Bluff City Middle School',
       'Boones Creek Middle School',
       'Bradley Academy - An Arts Integrated School',
       'Brentwood High School', 'Brentwood Middle School',
       "Brown's Chapel Elementary School", 'Buchanan Elementary',
       'Buena Vista Elementary', 'Byars Dowdy Elementary',
       'Byrns L Darden Elementary', 'Caldwell Elementary',
       'Cameron College Preparatory', 'Carmel Elementary',
       'Carroll Oakland Elementary', 'Carter-Lawrence Elementary',
       'Cason Lane Academy', 'Castle Heights Elementary',
       'Centennial Elementary', 'Centennial High School',
       'Central Elementary', "Chapman's Retreat Elementary",
       'Charlotte Park Elementary', 'Cherokee Elementary',
       'Clarksville High School', 'Clovercroft Elementary School',
       'Clyde Riggs Elementary', 'Cockrill Elementary',
       'Coles Ferry Elementary', 'Colonial Heights Middle',
       'Columbia Central High School', 'Crieve Hall Elementary',
       'Crockett Elementary', 'Croft Middle', 'Cumberland Elementary',
       'Cumberland Heights Elementary', 'Dan Mills Elementary',
       'Dickson County High School', 'Dickson Elementary',
       'Dickson Middle School', 'Discovery School',
       'Dobyns - Bennett High', 'Donelson Middle', 'E B Wilson',
       'E. A. Cox Middle School', 'Eakin Elementary',
       'East End Preparatory School', 'East Montgomery Elementary',
       'East Side Elementary', 'Edmondson Elementary',
       'Elzie D Patton Elementary School', 'Emmett Elementary',
       'Erma Siegel Elementary', 'Fairmont Elementary',
       'Fairmount Elementary', 'Fairview Elementary',
       'Fairview High School', 'Fairview Middle School',
       'Fall-Hamilton Elementary', 'Franklin Elementary',
       'Franklin High School', 'Fred J Page High School',
       'Fred J Page Middle School', 'Freedom Middle School',
       'Gallatin Senior High School', 'Gene W. Brown Elementary',
       'George A Whitten Elementary', 'Glencliff Elementary',
       'Glencliff High School', 'Glendale Elementary',
       'Glenellen Elementary', 'Glengarry Elementary', 'Glenn Elementary',
       'Glenview Elementary', 'Goodlettsville Elementary',
       'Goodlettsville Middle', 'Gower Elementary', 'Gra-Mar Middle',
       'Granbery Elementary', 'Grassland Elementary',
       'Grassland Middle School', 'Guild Elementary', 'H. G. Hill Middle',
       'Happy Valley Elementary', 'Harold B. Williams Elementary School',
       'Harpeth Valley Elementary', 'Harris Middle School',
       'Hattie Cotton Elementary', 'Haynes Middle',
       'Haynesfield Elementary', 'Haywood Elementary',
       'Hazelwood Elementary', 'Head Middle',
       'Hendersonville High School', 'Hickman Elementary',
       'Highland Park Elementary', 'Hillsboro Elementary/ Middle School',
       'Hillsboro High', 'Hillwood High', 'Hobgood Elementary',
       'Holloway High School', 'Holston Valley Middle School',
       'Holston View Elementary', 'Homer Pittard Campus School',
       'Howard Elementary', 'Hull-Jackson Elementary', 'Hume - Fogg High',
       'Hunters Bend Elementary', 'Hunters Lane High',
       'Indian Lake Elementary', 'Indian Springs Elementary',
       'Inglewood Elementary', 'Isaac Litton Middle',
       'Isaiah T. Creswell Middle', 'J E Woodard Elementary',
       'J W Wiseman Elementary', 'J. Brown Elementary',
       'J. R. Baker Elementary', 'Jack Anderson Elementary',
       'Jackson Elementary', 'Jefferson Elementary', 'Jere Baxter Middle',
       'Jim Satterfield Middle School', 'Joe Shafer Middle School',
       'John Adams Elementary', 'John B. Whitsitt Elementary',
       'John Early Middle', 'John Overton High',
       'John Pittard Elementary', 'John Trotwood Moore Middle',
       'Johnson Elementary', 'Jones Elementary', 'Julia Green Elementary',
       'K I P P Academy Nashville', 'Kennedy Elementary',
       'Kenrose Elementary', 'Kenwood Elementary', 'Kenwood High School',
       'Kenwood Middle School', 'Ketron Elementary School',
       'Kirkpatrick Elementary', 'Lake Ridge Elementary',
       'Lakeside Park Elementary', 'Lakeview Elementary',
       'Lakeview Elementary School', 'Lavergne High School',
       'Lavergne Lake Elementary School', 'Lavergne Middle School',
       'Lead Prep Southeast', 'Learning Way Elementary',
       'Lebanon High School', 'Liberty Bell Middle School',
       'Liberty Collegiate Academy', 'Liberty Elementary',
       'Lincoln Elementary', 'Lipscomb Elementary',
       'Lockeland Elementary', 'Longview Elementary School',
       'Madison Creek Elementary', 'Maplewood High',
       'Margaret Allen Middle', 'Martin Luther King Junior School',
       'Marvin Wright Elementary School',
       'May Werthan Shayne Elementary School', 'McDowell Elementary',
       'McFadden School Of Excellence', 'McGavock Elementary',
       'McGavock High', 'McMurray Middle', 'Meigs Middle',
       'Middle College High', 'Miller Perry Elementary',
       'Millersville Elementary', 'Minglewood Elementary',
       'Mitchell-Neilson Elementary', 'Moore Elementary',
       'Moore Magnet Elementary', 'Moses McKissack Middle',
       'Mountain View Elementary', 'Mt. Juliet Elementary',
       'Mt. Juliet High School', 'Mt. Juliet Middle School',
       'Mt. Pleasant Middle Visual Perform. Arts', 'Murrell School',
       'Nannie Berry Elementary', 'Napier Elementary',
       'Nashville Big Picture High School', 'Nashville Prep',
       'Nashville School Of The Arts', 'New Providence Middle School',
       'New Vision Academy', 'Norman Binkley Elementary',
       'Norman Smith Elementary', 'North Middle School',
       'North Side Elementary', 'Northeast Elementary',
       'Northeast High School', 'Northeast Middle School',
       'Northfield Elementary', 'Northwest High School',
       'Oak View Elementary School', 'Oakland High School',
       'Oakland Middle School', 'Oakmont Elementary',
       'Old Center Elementary', 'Paragon Mills Elementary',
       'Park Avenue Elementary', 'Pearl-Cohn High',
       'Pearre Creek Elementary School', 'Pennington Elementary',
       'Percy Priest Elementary', 'Pickett County Elementary',
       'Pickett County High School', 'Poplar Grove 5-8',
       'Poplar Grove K-4', 'Portland East Middle School',
       'Portland Gateview Elementary School', 'Portland High School',
       'Portland West Middle School', 'R Howell Elementary',
       'Ravenwood High School', 'Renaissance High School',
       'Richview Middle School', 'Ringgold Elementary',
       'Riverdale High School', 'Riverside Elementary',
       'Robert Churchwell Elementary', 'Robert E Ellis Middle',
       'Robert E. Lilliard Elementary', 'Robinson Middle School',
       'Rock Springs Elementary', 'Roosevelt Elementary',
       'Rose Park Middle', 'Rosebank Elementary', 'Rossview Elementary',
       'Rossview High School', 'Rossview Middle School',
       'Roy L Waldron Elementary', 'Rucker Stewart Middle',
       'Rutland Elementary', 'STEM Preparatory Academy',
       'Sam Houston Elementary', 'Sango Elementary', 'Scales Elementary',
       'Scales Elementary School', 'Science Hill High School',
       'Sevier Middle School', 'Shelbyville Central High School',
       'Shwab Elementary', 'Siegel High School', 'Siegel Middle School',
       'South Side Elementary', 'Southside Elementary',
       'Spencer Elementary', 'Spring Hill Elementary',
       'Spring Hill High School', 'Spring Hill Middle School',
       'Spring Station Middle School', 'Stanford Elementary',
       'Station Camp Elementary', 'Station Camp High School',
       'Station Camp Middle School', 'Stoner Creek Elementary',
       'Stratford High', 'Sullivan East High School',
       'Sullivan Gardens K-8', 'Sullivan North High School',
       'Sullivan South High School', 'Summit High School',
       'Sunset Elementary School', 'Sunset Middle School',
       'Sylvan Park Elementary', 'T. W. Hunter Middle School',
       'Tennessee High School', 'Tennessee Online Public School',
       'The Discovery School',
       'The Middle College @ Austin Peay State University',
       'Thomas Magnet', 'Tom Joy Elementary', 'Towne Acres Elementary',
       'Trinity Elementary', 'Trousdale County Elementary',
       'Trousdale County High School', 'Tuckers Crossroads Elementary',
       'Tusculum Elementary', 'Two Rivers Middle', 'Una Elementary',
       'Union Elementary School', 'V G Hawkins Middle School',
       'Vance Middle School', 'Vena Stuart Elementary',
       'W A Wright Elementary', 'Walnut Grove Elementary',
       'Walter Hill Elementary', 'Walter J. Baird Middle School',
       'Walton Ferry Elementary', 'Warner Elementary',
       'Washington Elementary', 'Watauga Elementary',
       'Watertown Elementary', 'Watertown High School',
       'Watt Hardison Elementary', 'Weaver Elementary',
       'West Creek Elementary School', 'West Creek High School',
       'West Creek Middle School', 'West Elementary', 'West End Middle',
       'West Wilson Middle School', 'Westmeade Elementary',
       'Westwood Elementary School',
       'White House Heritage Elementary School',
       'White House Heritage High School', 'White House High School',
       'White House Middle School', 'Whitthorne Middle School',
       'Whitworth-Buchanan Middle School', 'William Henry Oliver Middle',
       'Wilson Central High School', 'Wilson Elementary School',
       'Winfree Bryant Middle School', 'Winstead Elementary School',
       'Woodland Elementary', 'Woodland Middle School', 'Wright Middle'],
      dtype=object)

In [13]:
#no of unique categories in a column
school['name'].nunique()

341

In [14]:
school['name'].value_counts()

name
Liberty Elementary                     3
South Side Elementary                  2
Johnson Elementary                     2
Eakin Elementary                       2
Rock Springs Elementary                2
                                      ..
Hillsboro Elementary/ Middle School    1
Highland Park Elementary               1
Hickman Elementary                     1
Hendersonville High School             1
Wright Middle                          1
Name: count, Length: 341, dtype: int64

In [15]:
#count missing values
school.isna().sum()

name                   0
school_rating          0
size                   0
reduced_lunch          0
state_percentile_16    0
state_percentile_15    6
stu_teach_ratio        0
school_type            0
avg_score_15           6
avg_score_16           0
full_time_teachers     0
percent_black          0
percent_white          0
percent_asian          0
percent_hispanic       0
dtype: int64

In [16]:
school.isnull().sum()

name                   0
school_rating          0
size                   0
reduced_lunch          0
state_percentile_16    0
state_percentile_15    6
stu_teach_ratio        0
school_type            0
avg_score_15           6
avg_score_16           0
full_time_teachers     0
percent_black          0
percent_white          0
percent_asian          0
percent_hispanic       0
dtype: int64